import "dotenv/config";
import { PrismaClient, VehicleCondition, VehicleStatus, BodyType, FuelType, Transmission, Drivetrain } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const vehicles = [
  // COUPE
  {
    slug: "2024-bmw-m4-competition",
    make: "BMW",
    model: "M4",
    trim: "Competition xDrive",
    year: 2024,
    price: 84900,
    mileage: 1250,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Sapphire Black",
    interiorColor: "Black Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Experience the ultimate driving machine. Equipped with M xDrive all-wheel drive, premium executive packages, and a high-performance inline-six twin-power turbo engine.",
    features: ["Adaptive M Suspension", "M Carbon Bucket Seats", "Head-Up Display", "Harman Kardon Audio", "Laserlights"],
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&fit=crop"],
    mpgCity: 16,
    mpgHighway: 23,
    engineInfo: "3.0L Twin-Turbo I6",
    horsepower: 503,
  },
  {
    slug: "2024-mercedes-amg-gt-63",
    make: "Mercedes-Benz",
    model: "AMG GT",
    trim: "63 S",
    year: 2024,
    price: 179900,
    mileage: 890,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Obsidian Black",
    interiorColor: "Red Nappa Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Performance meets handcrafted luxury. Featuring carbon fiber aerodynamics packages, AMG sport active exhaust, and elite performance suspension.",
    features: ["AMG Performance Exhaust", "Carbon Fiber Package", "Burmester Sound", "Rear Axle Steering", "Dynamic Plus Package"],
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&fit=crop"],
    mpgCity: 15,
    mpgHighway: 20,
    engineInfo: "4.0L Twin-Turbo V8",
    horsepower: 630,
  },
  {
    slug: "2023-porsche-911-carrera-s",
    make: "Porsche",
    model: "911",
    trim: "Carrera S",
    year: 2023,
    price: 128500,
    mileage: 4200,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.RWD,
    exteriorColor: "Guards Red",
    interiorColor: "Black Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Benchmark performance. Clean history, 111-point certified check completed. Loaded with Sport Chrono and active dynamic chassis control.",
    features: ["Sport Chrono Package", "PASM Sport Suspension", "Bose Surround Sound", "Premium Package", "Sport Exhaust"],
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&fit=crop"],
    mpgCity: 18,
    mpgHighway: 24,
    engineInfo: "3.0L Twin-Turbo H6",
    horsepower: 443,
  },
  {
    slug: "2024-chevrolet-corvette-stingray",
    make: "Chevrolet",
    model: "Corvette",
    trim: "Stingray 3LT",
    year: 2024,
    price: 78900,
    mileage: 950,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.RWD,
    exteriorColor: "Torch Red",
    interiorColor: "Adrenaline Red Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Mid-engine masterpiece. Incredible track capabilities combined with premium daily comforts.",
    features: ["Performance Exhaust", "Magnetic Ride Control", "Head-Up Display", "GT2 Bucket Seats", "Front Lift Adjustable height"],
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&fit=crop"],
    mpgCity: 16,
    mpgHighway: 24,
    engineInfo: "6.2L V8",
    horsepower: 495,
  },
  // SEDAN
  {
    slug: "2024-tesla-model-s-plaid",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid",
    year: 2024,
    price: 89990,
    mileage: 320,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Pearl White",
    interiorColor: "Black Premium Vegan",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Exceptional speed, electric range, and modern screen interfaces. 0-60 mph in under 2 seconds.",
    features: ["Autopilot", "Full Self-Driving Capability", "17\" Cinematic Display", "Yoke Steering", "Plaid Badging"],
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&fit=crop"],
    engineInfo: "Tri Motor Electric",
    horsepower: 1020,
  },
  {
    slug: "2023-audi-rs7-performance",
    make: "Audi",
    model: "RS7",
    trim: "Performance",
    year: 2023,
    price: 119800,
    mileage: 8700,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Nardo Gray",
    interiorColor: "Valcona Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Sportback beauty with racing pedigree. Premium acoustics, driver assistance, and dynamic package.",
    features: ["RS Sport Exhaust", "Carbon Optic Package", "Bang & Olufsen 3D Sound", "Panoramic Sunroof", "Dynamic Steering"],
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&fit=crop"],
    mpgCity: 15,
    mpgHighway: 22,
    engineInfo: "4.0L Twin-Turbo V8",
    horsepower: 621,
  },
  {
    slug: "2023-toyota-camry-xse",
    make: "Toyota",
    model: "Camry",
    trim: "XSE V6",
    year: 2023,
    price: 35400,
    mileage: 12500,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FWD,
    exteriorColor: "Wind Chill Pearl",
    interiorColor: "Cockpit Red Leather",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Sporty aesthetic with legendary Toyota reliability. V6 engine provides surprising performance.",
    features: ["JBL Premium Audio", "Panoramic Roof", "Leather Sport Seats", "Toyota Safety Sense", "Heated Seats"],
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&fit=crop"],
    mpgCity: 22,
    mpgHighway: 33,
    engineInfo: "3.5L V6",
    horsepower: 301,
  },
  // SUV
  {
    slug: "2024-range-rover-sport-dynamic",
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "Dynamic SE",
    year: 2024,
    price: 83500,
    mileage: 2100,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Santorini Black",
    interiorColor: "Ebony Windsor Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Premium capability and design. Adaptive air suspension, off-road controls, and luxury styling.",
    features: ["Air Suspension", "Terrain Response 2", "Meridian Surround Sound", "Panoramic Roof", "3D Surround Camera"],
    images: ["https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&fit=crop"],
    mpgCity: 19,
    mpgHighway: 26,
    engineInfo: "3.0L I6 Mild Hybrid",
    horsepower: 395,
  },
  {
    slug: "2024-hyundai-ioniq-5-limited",
    make: "Hyundai",
    model: "IONIQ 5",
    trim: "Limited AWD",
    year: 2024,
    price: 52600,
    mileage: 1800,
    bodyType: BodyType.SUV,
    fuelType: FuelType.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Lucid Blue",
    interiorColor: "Gray Leatherette",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Ultra-fast charging, retro-modern design, and top safety features.",
    features: ["Vehicle-to-Load", "Augmented Reality HUD", "Relaxation Seats", "Highway Driving Assist 2", "Vision Roof"],
    images: ["https://images.unsplash.com/photo-1702487424125-04be398f3a5a?w=800&fit=crop"],
    engineInfo: "Dual Motor Electric",
    horsepower: 320,
  },
  {
    slug: "2023-lexus-rx-350h",
    make: "Lexus",
    model: "RX",
    trim: "350h F Sport",
    year: 2023,
    price: 56800,
    mileage: 11200,
    bodyType: BodyType.SUV,
    fuelType: FuelType.HYBRID,
    transmission: Transmission.CVT,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Matador Red",
    interiorColor: "Black NuLuxe",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Exceptional efficiency and luxurious ride. Certified pre-owned peace of mind included.",
    features: ["Mark Levinson Audio", "Panoramic Roof", "Digital Rearview Mirror", "F Sport Styling", "Heated and Ventilated Seats"],
    images: ["https://images.unsplash.com/photo-1625231334695-19dc14eded3b?w=800&fit=crop"],
    mpgCity: 37,
    mpgHighway: 34,
    engineInfo: "2.5L Hybrid I4",
    horsepower: 246,
  },
  // TRUCK
  {
    slug: "2024-ford-f150-lariat",
    make: "Ford",
    model: "F-150",
    trim: "Lariat SuperCrew",
    year: 2024,
    price: 62300,
    mileage: 3400,
    bodyType: BodyType.TRUCK,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FOUR_WD,
    exteriorColor: "Antimatter Blue",
    interiorColor: "Baja Tan Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "America's favorite truck, loaded with technology and ready for work or play.",
    features: ["Max Tow Package", "360-Degree Camera", "B&O Sound System", "Pro Power Onboard", "Sync 4 with 12\" Screen"],
    images: ["https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=800&fit=crop"],
    mpgCity: 18,
    mpgHighway: 24,
    engineInfo: "3.5L EcoBoost V6",
    horsepower: 400,
  },
  // HATCHBACK
  {
    slug: "2023-honda-civic-type-r",
    make: "Honda",
    model: "Civic",
    trim: "Type R",
    year: 2023,
    price: 44900,
    mileage: 6800,
    bodyType: BodyType.HATCHBACK,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.MANUAL,
    drivetrain: Drivetrain.FWD,
    exteriorColor: "Championship White",
    interiorColor: "Red Suede Sport",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Pure driving connection. Exceptional manual shift feel, high-performance turbo, and razor-sharp steering.",
    features: ["Rev Match Control", "Brembo Brakes", "Limited Slip Differential", "LogR Data Logger", "Triple Exhaust"],
    images: ["https://images.unsplash.com/photo-1679239872589-e0040e498998?w=800&fit=crop"],
    mpgCity: 22,
    mpgHighway: 28,
    engineInfo: "2.0L Turbo I4",
    horsepower: 315,
  },
];

async function main() {
  console.log("Seeding Dealership Settings...");
  await prisma.dealershipSettings.upsert({
    where: { id: "default" },
    update: {},
    create: {
      name: "AutoLot",
      tagline: "Your Premier Destination for Quality Vehicles",
      phone: "(555) 123-4567",
      email: "info@autolot.com",
      address: "123 Auto Drive, Springfield, IL 62701",
      mondayHours: "9:00 AM - 8:00 PM",
      tuesdayHours: "9:00 AM - 8:00 PM",
      wednesdayHours: "9:00 AM - 8:00 PM",
      thursdayHours: "9:00 AM - 8:00 PM",
      fridayHours: "9:00 AM - 8:00 PM",
      saturdayHours: "9:00 AM - 6:00 PM",
      sundayHours: "Closed",
      financingDefaultAPR: 6.9,
    },
  });

  console.log("Seeding Vehicles...");
  for (const v of vehicles) {
    await prisma.vehicle.upsert({
      where: { slug: v.slug },
      update: {},
      create: v,
    });
  }

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
