import "dotenv/config";
import { PrismaClient, VehicleCondition, VehicleStatus, BodyType, FuelType, Transmission, Drivetrain } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const vehicles = [
  // COUPE
  {
    slug: "2024-bmw-m4-competition",
    make: "BMW",
    model: "M4",
    trim: "Competition xDrive",
    year: 2024,
    price: 84900,
    mileage: 1250,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Sapphire Black",
    interiorColor: "Black Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Experience the ultimate driving machine. Equipped with M xDrive all-wheel drive, premium executive packages, and a high-performance inline-six twin-power turbo engine.",
    features: ["Adaptive M Suspension", "M Carbon Bucket Seats", "Head-Up Display", "Harman Kardon Audio", "Laserlights"],
    images: ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&fit=crop"],
    mpgCity: 16,
    mpgHighway: 23,
    engineInfo: "3.0L Twin-Turbo I6",
    horsepower: 503,
  },
  {
    slug: "2024-mercedes-amg-gt-63",
    make: "Mercedes-Benz",
    model: "AMG GT",
    trim: "63 S",
    year: 2024,
    price: 179900,
    mileage: 890,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Obsidian Black",
    interiorColor: "Red Nappa Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Performance meets handcrafted luxury. Featuring carbon fiber aerodynamics packages, AMG sport active exhaust, and elite performance suspension.",
    features: ["AMG Performance Exhaust", "Carbon Fiber Package", "Burmester Sound", "Rear Axle Steering", "Dynamic Plus Package"],
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&fit=crop"],
    mpgCity: 15,
    mpgHighway: 20,
    engineInfo: "4.0L Twin-Turbo V8",
    horsepower: 630,
  },
  {
    slug: "2023-porsche-911-carrera-s",
    make: "Porsche",
    model: "911",
    trim: "Carrera S",
    year: 2023,
    price: 128500,
    mileage: 4200,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.RWD,
    exteriorColor: "Guards Red",
    interiorColor: "Black Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Benchmark performance. Clean history, 111-point certified check completed. Loaded with Sport Chrono and active dynamic chassis control.",
    features: ["Sport Chrono Package", "PASM Sport Suspension", "Bose Surround Sound", "Premium Package", "Sport Exhaust"],
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&fit=crop"],
    mpgCity: 18,
    mpgHighway: 24,
    engineInfo: "3.0L Twin-Turbo H6",
    horsepower: 443,
  },
  {
    slug: "2024-chevrolet-corvette-stingray",
    make: "Chevrolet",
    model: "Corvette",
    trim: "Stingray 3LT",
    year: 2024,
    price: 78900,
    mileage: 950,
    bodyType: BodyType.COUPE,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.RWD,
    exteriorColor: "Torch Red",
    interiorColor: "Adrenaline Red Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Mid-engine masterpiece. Incredible track capabilities combined with premium daily comforts.",
    features: ["Performance Exhaust", "Magnetic Ride Control", "Head-Up Display", "GT2 Bucket Seats", "Front Lift Adjustable height"],
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&fit=crop"],
    mpgCity: 16,
    mpgHighway: 24,
    engineInfo: "6.2L V8",
    horsepower: 495,
  },
  // SEDAN
  {
    slug: "2024-tesla-model-s-plaid",
    make: "Tesla",
    model: "Model S",
    trim: "Plaid",
    year: 2024,
    price: 89990,
    mileage: 320,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Pearl White",
    interiorColor: "Black Premium Vegan",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Exceptional speed, electric range, and modern screen interfaces. 0-60 mph in under 2 seconds.",
    features: ["Autopilot", "Full Self-Driving Capability", "17\" Cinematic Display", "Yoke Steering", "Plaid Badging"],
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&fit=crop"],
    engineInfo: "Tri Motor Electric",
    horsepower: 1020,
  },
  {
    slug: "2023-audi-rs7-performance",
    make: "Audi",
    model: "RS7",
    trim: "Performance",
    year: 2023,
    price: 119800,
    mileage: 8700,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Nardo Gray",
    interiorColor: "Valcona Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Sportback beauty with racing pedigree. Premium acoustics, driver assistance, and dynamic package.",
    features: ["RS Sport Exhaust", "Carbon Optic Package", "Bang & Olufsen 3D Sound", "Panoramic Sunroof", "Dynamic Steering"],
    images: ["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&fit=crop"],
    mpgCity: 15,
    mpgHighway: 22,
    engineInfo: "4.0L Twin-Turbo V8",
    horsepower: 621,
  },
  {
    slug: "2023-toyota-camry-xse",
    make: "Toyota",
    model: "Camry",
    trim: "XSE V6",
    year: 2023,
    price: 35400,
    mileage: 12500,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FWD,
    exteriorColor: "Wind Chill Pearl",
    interiorColor: "Cockpit Red Leather",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Sporty aesthetic with legendary Toyota reliability. V6 engine provides surprising performance.",
    features: ["JBL Premium Audio", "Panoramic Roof", "Leather Sport Seats", "Toyota Safety Sense", "Heated Seats"],
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&fit=crop"],
    mpgCity: 22,
    mpgHighway: 33,
    engineInfo: "3.5L V6",
    horsepower: 301,
  },
  // SUV
  {
    slug: "2024-range-rover-sport-dynamic",
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "Dynamic SE",
    year: 2024,
    price: 83500,
    mileage: 2100,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Santorini Black",
    interiorColor: "Ebony Windsor Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Premium capability and design. Adaptive air suspension, off-road controls, and luxury styling.",
    features: ["Air Suspension", "Terrain Response 2", "Meridian Surround Sound", "Panoramic Roof", "3D Surround Camera"],
    images: ["https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&fit=crop"],
    mpgCity: 19,
    mpgHighway: 26,
    engineInfo: "3.0L I6 Mild Hybrid",
    horsepower: 395,
  },
  {
    slug: "2024-hyundai-ioniq-5-limited",
    make: "Hyundai",
    model: "IONIQ 5",
    trim: "Limited AWD",
    year: 2024,
    price: 52600,
    mileage: 1800,
    bodyType: BodyType.SUV,
    fuelType: FuelType.ELECTRIC,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Lucid Blue",
    interiorColor: "Gray Leatherette",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Ultra-fast charging, retro-modern design, and top safety features.",
    features: ["Vehicle-to-Load", "Augmented Reality HUD", "Relaxation Seats", "Highway Driving Assist 2", "Vision Roof"],
    images: ["https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&fit=crop"],
    engineInfo: "Dual Motor Electric",
    horsepower: 320,
  },
  {
    slug: "2023-lexus-rx-350h",
    make: "Lexus",
    model: "RX",
    trim: "350h F Sport",
    year: 2023,
    price: 56800,
    mileage: 11200,
    bodyType: BodyType.SUV,
    fuelType: FuelType.HYBRID,
    transmission: Transmission.CVT,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Matador Red",
    interiorColor: "Black NuLuxe",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Exceptional efficiency and luxurious ride. Certified pre-owned peace of mind included.",
    features: ["Mark Levinson Audio", "Panoramic Roof", "Digital Rearview Mirror", "F Sport Styling", "Heated and Ventilated Seats"],
    images: ["https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&fit=crop"],
    mpgCity: 37,
    mpgHighway: 34,
    engineInfo: "2.5L Hybrid I4",
    horsepower: 246,
  },
  // TRUCK
  {
    slug: "2024-ford-f150-lariat",
    make: "Ford",
    model: "F-150",
    trim: "Lariat SuperCrew",
    year: 2024,
    price: 62300,
    mileage: 3400,
    bodyType: BodyType.TRUCK,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FOUR_WD,
    exteriorColor: "Antimatter Blue",
    interiorColor: "Baja Tan Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "America's favorite truck, loaded with technology and ready for work or play.",
    features: ["Max Tow Package", "360-Degree Camera", "B&O Sound System", "Pro Power Onboard", "Sync 4 with 12\" Screen"],
    images: ["https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=800&fit=crop"],
    mpgCity: 18,
    mpgHighway: 24,
    engineInfo: "3.5L EcoBoost V6",
    horsepower: 400,
  },
  // HATCHBACK
  {
    slug: "2023-honda-civic-type-r",
    make: "Honda",
    model: "Civic",
    trim: "Type R",
    year: 2023,
    price: 44900,
    mileage: 6800,
    bodyType: BodyType.HATCHBACK,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.MANUAL,
    drivetrain: Drivetrain.FWD,
    exteriorColor: "Championship White",
    interiorColor: "Red Suede Sport",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Pure driving connection. Exceptional manual shift feel, high-performance turbo, and razor-sharp steering.",
    features: ["Rev Match Control", "Brembo Brakes", "Limited Slip Differential", "LogR Data Logger", "Triple Exhaust"],
    images: ["https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&fit=crop"],
    mpgCity: 22,
    mpgHighway: 28,
    engineInfo: "2.0L Turbo I4",
    horsepower: 315,
  },
  // REAL CONVERTED VEHICLES
  {
    slug: "2022-range-rover-autobiography",
    make: "Land Rover",
    model: "Range Rover",
    trim: "Autobiography LWB",
    year: 2022,
    price: 185000,
    mileage: 18500,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Santorini Black",
    interiorColor: "Cream Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "A pinnacle of luxury motoring. Finished in Santorini Black over cream leather interior.",
    features: ["Autobiography Package", "Panoramic Roof", "Meridian Signature Sound", "Heated & Cooled Seats"],
    images: ["/vehicles/rr-autobiography-1.jpg", "/vehicles/rr-autobiography-2.jpg", "/vehicles/rr-autobiography-3.jpg", "/vehicles/rr-autobiography-4.jpg", "/vehicles/rr-autobiography-5.jpg"],
    mpgCity: 14,
    mpgHighway: 19,
    engineInfo: "5.0L Supercharged V8",
    horsepower: 518,
  },
  {
    slug: "2019-range-rover-sport-supercharged",
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "Supercharged",
    year: 2019,
    price: 95000,
    mileage: 42000,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Indus Silver",
    interiorColor: "Black Leather",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Athletic performance meets all-terrain capability with 518hp V8.",
    features: ["Sport Suspension", "Panoramic Roof", "Meridian Sound", "Heated Leather Seats"],
    images: ["/vehicles/rr-sport-1.jpg", "/vehicles/rr-sport-2.jpg", "/vehicles/rr-sport-3.jpg", "/vehicles/rr-sport-4.jpg", "/vehicles/rr-sport-5.jpg"],
    mpgCity: 14,
    mpgHighway: 19,
    engineInfo: "5.0L Supercharged V8",
    horsepower: 518,
  },
  {
    slug: "2025-toyota-land-cruiser-prado",
    make: "Toyota",
    model: "Land Cruiser Prado",
    trim: "VX",
    year: 2025,
    price: 72000,
    mileage: 0,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FOUR_WD,
    exteriorColor: "White / Black Roof",
    interiorColor: "Black Leather",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Brand new 2025 Toyota Land Cruiser Prado VX with zero miles.",
    features: ["Multi-Terrain Select", "Crawl Control", "Panoramic Sunroof", "Toyota Safety Sense"],
    images: ["/vehicles/lc-prado-1.jpg", "/vehicles/lc-prado-2.jpg", "/vehicles/lc-prado-3.jpg", "/vehicles/lc-prado-4.jpg", "/vehicles/lc-prado-5.jpg"],
    mpgCity: 18,
    mpgHighway: 24,
    engineInfo: "2.8L Turbo Diesel / 2.4L Turbo",
    horsepower: 326,
  },
  {
    slug: "2023-land-rover-defender-110",
    make: "Land Rover",
    model: "Defender 110",
    trim: "X-Dynamic SE",
    year: 2023,
    price: 88500,
    mileage: 12400,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Fuji White",
    interiorColor: "Black / Ebony",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "Rugged yet ultra-refined. Fuji White Land Rover Defender 110 X-Dynamic SE.",
    features: ["Off-Road Pack", "Air Suspension", "3D Surround Camera", "Meridian Sound"],
    images: ["/vehicles/converted/IMG_3452.jpg", "/vehicles/converted/IMG_3461.jpg"],
    mpgCity: 17,
    mpgHighway: 22,
    engineInfo: "3.0L Turbocharged I6 MHEV",
    horsepower: 395,
  },
  {
    slug: "2023-dodge-charger-srt-hellcat",
    make: "Dodge",
    model: "Charger",
    trim: "SRT Hellcat Widebody",
    year: 2023,
    price: 82900,
    mileage: 6800,
    bodyType: BodyType.SEDAN,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.RWD,
    exteriorColor: "Yellow / Go Mango",
    interiorColor: "Black Laguna Leather",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "717hp supercharged 6.2L HEMI V8 muscle sedan.",
    features: ["Widebody Package", "Brembo Brakes", "Laguna Leather Seats", "Harman Kardon Audio"],
    images: [
      "/vehicles/converted/IMG_3661.jpg",
      "/vehicles/converted/IMG_3662.jpg",
      "/vehicles/converted/IMG_3663.jpg",
      "/vehicles/converted/IMG_3664.jpg",
      "/vehicles/converted/IMG_3666.jpg",
      "/vehicles/converted/IMG_3667.jpg",
      "/vehicles/converted/IMG_3668.jpg",
      "/vehicles/converted/IMG_3669.jpg",
      "/vehicles/converted/IMG_3670.jpg",
    ],
    mpgCity: 12,
    mpgHighway: 21,
    engineInfo: "6.2L Supercharged HEMI V8",
    horsepower: 717,
  },
  {
    slug: "2022-ram-1500-trx",
    make: "RAM",
    model: "1500",
    trim: "TRX 4x4",
    year: 2022,
    price: 89900,
    mileage: 15300,
    bodyType: BodyType.TRUCK,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.FOUR_WD,
    exteriorColor: "Diamond Black Crystal",
    interiorColor: "Black Leather",
    condition: VehicleCondition.USED,
    status: VehicleStatus.AVAILABLE,
    description: "702hp supercharged V8 performance pickup truck.",
    features: ["Bilstein Black Hawk shocks", "TRX Level 2 Group", "Head-Up Display", "Harman Kardon Sound"],
    images: [
      "/vehicles/converted/IMG_3676.jpg",
      "/vehicles/converted/IMG_3677.jpg",
      "/vehicles/converted/IMG_3678.jpg",
      "/vehicles/converted/IMG_3681.jpg",
      "/vehicles/converted/IMG_3682.jpg",
    ],
    mpgCity: 10,
    mpgHighway: 14,
    engineInfo: "6.2L Supercharged HEMI V8",
    horsepower: 702,
  },
  {
    slug: "2024-acura-mdx-aspec",
    make: "Acura",
    model: "MDX",
    trim: "A-Spec Package",
    year: 2024,
    price: 61500,
    mileage: 4200,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Red Milano Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Platinum White Pearl 3-row luxury crossover with A-Spec package.",
    features: ["Super Handling AWD", "ELS Studio 3D Sound", "Milano Leather Seats", "Panoramic Moonroof"],
    images: [
      "/vehicles/converted/IMG_3684.jpg",
      "/vehicles/converted/IMG_3686.jpg",
      "/vehicles/converted/IMG_3688.jpg",
    ],
    mpgCity: 19,
    mpgHighway: 25,
    engineInfo: "3.5L V6",
    horsepower: 290,
  },
  {
    slug: "2023-mercedes-amg-g63",
    make: "Mercedes-Benz",
    model: "G-Class",
    trim: "AMG G 63",
    year: 2023,
    price: 198000,
    mileage: 9100,
    bodyType: BodyType.SUV,
    fuelType: FuelType.GASOLINE,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Polar White",
    interiorColor: "Red Quilted Nappa Leather",
    condition: VehicleCondition.CERTIFIED,
    status: VehicleStatus.AVAILABLE,
    description: "Iconic Polar White Mercedes-AMG G 63 with red quilted leather interior.",
    features: ["AMG Night Package", "Red Quilted Leather", "Burmester Surround Sound", "Carbon Fiber Trim"],
    images: [
      "/vehicles/converted/IMG_3726.jpg",
      "/vehicles/converted/IMG_3727.jpg",
      "/vehicles/converted/IMG_3728.jpg",
      "/vehicles/converted/IMG_3729.jpg",
      "/vehicles/converted/IMG_3730.jpg",
    ],
    mpgCity: 13,
    mpgHighway: 16,
    engineInfo: "4.0L V8 Biturbo",
    horsepower: 577,
  },
  {
    slug: "2024-honda-crv-hybrid-sport-touring",
    make: "Honda",
    model: "CR-V Hybrid",
    trim: "Sport Touring AWD",
    year: 2024,
    price: 41200,
    mileage: 2500,
    bodyType: BodyType.SUV,
    fuelType: FuelType.HYBRID,
    transmission: Transmission.AUTOMATIC,
    drivetrain: Drivetrain.AWD,
    exteriorColor: "Canyon River Blue",
    interiorColor: "Black Leather w/ Orange Stitching",
    condition: VehicleCondition.NEW,
    status: VehicleStatus.AVAILABLE,
    description: "Canyon River Blue Honda CR-V Hybrid Sport Touring AWD with Bose Audio.",
    features: ["Bose Premium Audio", "Leather Seats w/ Orange Stitching", "Hands-Free Power Tailgate", "Honda Sensing"],
    images: [
      "/vehicles/converted/IMG_3824.jpg",
      "/vehicles/converted/IMG_3823.jpg",
      "/vehicles/converted/IMG_3830.jpg",
      "/vehicles/converted/IMG_3833.jpg",
      "/vehicles/converted/IMG_3817.jpg",
      "/vehicles/converted/IMG_3820.jpg",
      "/vehicles/converted/IMG_3821.jpg",
      "/vehicles/converted/IMG_3822.jpg",
    ],
    mpgCity: 40,
    mpgHighway: 34,
    engineInfo: "2.0L 4-Cylinder Hybrid",
    horsepower: 204,
  },
];

async function main() {
  console.log("Seeding Dealership Settings...");
  await prisma.dealershipSettings.upsert({
    where: { id: "default" },
    update: {},
    create: {
      name: "AutoLot",
      tagline: "Your Premier Destination for Quality Vehicles",
      phone: "(555) 123-4567",
      email: "info@autolot.com",
      address: "123 Auto Drive, Springfield, IL 62701",
      mondayHours: "9:00 AM - 8:00 PM",
      tuesdayHours: "9:00 AM - 8:00 PM",
      wednesdayHours: "9:00 AM - 8:00 PM",
      thursdayHours: "9:00 AM - 8:00 PM",
      fridayHours: "9:00 AM - 8:00 PM",
      saturdayHours: "9:00 AM - 6:00 PM",
      sundayHours: "Closed",
      financingDefaultAPR: 6.9,
    },
  });

  console.log("Seeding Vehicles...");
  for (const v of vehicles) {
    await prisma.vehicle.upsert({
      where: { slug: v.slug },
      update: {},
      create: v,
    });
  }

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
